Fixed script and completed first 2 pages

diff --git a/bin/spaceshare_run b/bin/spaceshare_run
--- a/bin/spaceshare_run
+++ b/bin/spaceshare_run
@@ -14,9 +14,13 @@ npx webpack
 # check if sqlite3 files exists
 FILE=./var/spaceshare.sqlite3
 if test -f "$FILE"; then
+	npx webpack --watch &
 	flask --app spaceshare --debug run --host 0.0.0.0 --port 8000 # run app
 else
-	echo "Error: can't find database var/spaceshare.sqlite3"
-    echo "Try: ./bin/spaceshare_db create"
-	exit 1
+	# echo "Error: can't find database var/spaceshare.sqlite3"
+    ./bin/spaceshare_db create
+    npx webpack --watch &
+    flask --app spaceshare --debug run --host 0.0.0.0 --port 8000
+	# echo "Try: ./bin/spaceshare_db create"
+	# exit 1
 fi
